#!/bin/bash

echo "Welcome to Shell/Bash Scripting"
echo "###############################"
echo
echo
#This script uninstalls Apache2 web server.
echo

echo "#############################"
echo "Uninstall Apache2 Webserver"
echo "#############################"

sudo systemctl status apache2
sudo rm -rf /var/www/html/*
sudo apt autoremove apache2 -y
